name: app_mobi_pharmacy
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '2.19.2'



#--------------- PACKAGES ------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^0.13.5
  bcrypt: ^1.1.3
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0

  # Icons provider: ^6.1.2 
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^3.0.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2
  shared_preferences: ^2.2.2

  provider: ^6.1.2
  connectivity_plus: ^5.0.1
  lottie: ^3.0.0

  appwrite: ^12.0.1
  badges: ^3.1.2


 
  cloudinary_public: ^0.23.1
  file_picker: ^8.0.0+1
  localstorage: ^5.0.0
  flutter_stripe: ^3.2.0
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  flutter_paypal_checkout: ^1.0.1

  timeago: ^3.6.1
  flutter_timer_countdown: ^1.0.7
  flutter_countdown_timer: ^4.1.0
  jiffy: ^6.2.1
  tiengviet: ^1.0.0
  dvhcvn: ^2.0.20240501
  flutter_paypal: ^0.0.8
  flutter_bcrypt: ^1.0.8
  flutter_tawkto: ^0.0.3
  currency_converter: ^0.0.4
  forex_currency_conversion: ^0.9.0
  address_picker_vn: ^0.3.2
  webview_flutter: ^2.8.0


  
  #--------------- ./ PACKAGES END ------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - ../assets/logos/
    - ../assets/images/content/
    - ../assets/images/banners/
    - ../assets/images/products/
    - ../assets/images/animations/
    - ../assets/icons/payment_methods/
    - ../assets/images/on_boarding_images/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: ../assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: ../assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: ../assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: ../assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: ../assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: ../assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: ../assets/fonts/Poppins-Bold.ttf
          weight: 800
       
